# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: objects.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\robjects.proto\x12\rsecondvariety\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0emessages.proto2\xac\x02\n\x0bObjectsServ\x12\x37\n\x06GetAll\x12\x14.secondvariety.Empty\x1a\x17.secondvariety.GObjects\x12;\n\x07GetById\x12\x18.secondvariety.GObjectId\x1a\x16.secondvariety.GObject\x12\x36\n\x04Post\x12\x16.secondvariety.GObject\x1a\x16.secondvariety.GObject\x12\x35\n\x03Put\x12\x16.secondvariety.GObject\x1a\x16.secondvariety.GObject\x12\x38\n\x06\x44\x65lete\x12\x18.secondvariety.GObjectId\x1a\x14.secondvariety.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'objects_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _OBJECTSSERV._serialized_start=114
  _OBJECTSSERV._serialized_end=414
# @@protoc_insertion_point(module_scope)
