# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: requests.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import duration_pb2 as google_dot_protobuf_dot_duration__pb2
import messages_pb2 as messages__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0erequests.proto\x12\rsecondvariety\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x0emessages.proto2\xf8\x03\n\x0bRequestServ\x12\x38\n\x06GetAll\x12\x14.secondvariety.Empty\x1a\x18.secondvariety.GRequests\x12=\n\x07GetById\x12\x19.secondvariety.GRequestId\x1a\x17.secondvariety.GRequest\x12=\n\x08GetByNum\x12\x18.secondvariety.GObjectId\x1a\x17.secondvariety.GRequest\x12\x44\n\x0eGetByObjectKod\x12\x18.secondvariety.GObjectId\x1a\x18.secondvariety.GRequests\x12\x38\n\x04Post\x12\x17.secondvariety.GRequest\x1a\x17.secondvariety.GRequest\x12\x37\n\x03Put\x12\x17.secondvariety.GRequest\x1a\x17.secondvariety.GRequest\x12\x39\n\x06\x44\x65lete\x12\x19.secondvariety.GRequestId\x1a\x14.secondvariety.Empty\x12=\n\x0b\x44\x65leteByNum\x12\x18.secondvariety.GObjectId\x1a\x14.secondvariety.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'requests_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUESTSERV._serialized_start=115
  _REQUESTSERV._serialized_end=619
# @@protoc_insertion_point(module_scope)
